apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub-deployment
  labels:
    app: bookclub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookclub
  template:
    metadata:
      labels:
        app: bookclub
    spec:
      containers:
        - name: bookclub
          image: 471112985503.dkr.ecr.us-east-1.amazonaws.com/bookclub-app:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
